"""Idempotent, original teaching samples and clearly marked synthetic test tones."""

import hashlib, json, wave
from pathlib import Path
import numpy as np
from sqlalchemy import select
from .db import users, objects, one, add, now


def key(name):
    return hashlib.sha256(("baxshi-v3-demo:" + name).encode()).hexdigest()[:32]


def seed_demo(engine, media):
    count = 0
    with engine.begin() as c:
        admin = (
            c.execute(
                select(users)
                .where(users.c.role == "super_admin", users.c.active == True)
                .order_by(users.c.id)
                .limit(1)
                .with_for_update()
            )
            .mappings()
            .first()
        )
        if not admin:
            return 0
        owner = admin["id"]
        for lesson in json.loads(
            (Path(__file__).parent / "demo_lessons.json").read_text()
        ):
            id = key("lesson:" + lesson["key"])
            if not one(c, objects, objects.c.id == id):
                add(c, "lesson", owner, {**lesson, "published": True}, id)
                count += 1
        asset = key("tone-asset")
        path = media / "assets" / asset
        if not one(c, objects, objects.c.id == asset):
            path.parent.mkdir(parents=True, exist_ok=True)
            sr = 16000
            t = np.arange(sr * 12) / sr
            notes = np.array(
                [220, 247, 262, 294, 262, 247, 220, 196, 220, 247, 262, 220]
            )
            freq = notes[np.floor(t).astype(int)]
            phase = 2 * np.pi * np.cumsum(freq) / sr
            envelope = 0.2 * (0.25 + 0.75 * np.sin(np.pi * (t % 1)) ** 2)
            pcm = (np.sin(phase) * envelope * 32767).astype("<i2")
            with wave.open(str(path), "wb") as w:
                w.setnchannels(1)
                w.setsampwidth(2)
                w.setframerate(sr)
                w.writeframes(pcm.tobytes())
            with path.open("rb") as f:
                sha = hashlib.file_digest(f, "sha256").hexdigest()
            add(
                c,
                "asset",
                owner,
                {
                    "path": str(path),
                    "sha256": sha,
                    "mime": "audio/wav",
                    "size": path.stat().st_size,
                },
                asset,
            )
        for school in ["xorazm", "qashqadaryo", "surxondaryo", "qoraqalpogiston"]:
            id = key("reference:" + school)
            if not one(c, objects, objects.c.id == id):
                add(
                    c,
                    "reference",
                    owner,
                    {
                        "title": "TEXNIK SINOV — doston ijrosi emas",
                        "master": "Baxshi AI sun’iy test signali",
                        "school": school,
                        "asset_id": asset,
                        "license_note": "Original synthetic sine tone generated by Baxshi AI for pipeline testing; no performer recording.",
                        "license_until": now() + 10 * 365 * 86400,
                        "active": True,
                        "technical_demo": True,
                    },
                    id,
                )
                count += 1
    return count
